"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deg2rad = exports.rad2deg = exports.cloneDeep = exports.clamp = exports.randomInt = exports.random = exports.nameToColor = exports.colorToChromaColor = exports.hexToColor = exports.colorToHex = exports.grayToColor = exports.colorToGray = exports.arrayToColor = exports.colorToArray = exports.colorDarken = exports.colorBrighten = exports.colorBlend = exports.hueOffset = exports.loadImage = void 0;
var image_1 = require("./image");
Object.defineProperty(exports, "loadImage", { enumerable: true, get: function () { return image_1.loadImage; } });
var colorComputation_1 = require("./colorComputation");
Object.defineProperty(exports, "hueOffset", { enumerable: true, get: function () { return colorComputation_1.hueOffset; } });
Object.defineProperty(exports, "colorBlend", { enumerable: true, get: function () { return colorComputation_1.colorBlend; } });
Object.defineProperty(exports, "colorBrighten", { enumerable: true, get: function () { return colorComputation_1.colorBrighten; } });
Object.defineProperty(exports, "colorDarken", { enumerable: true, get: function () { return colorComputation_1.colorDarken; } });
var colorConversion_1 = require("./colorConversion");
Object.defineProperty(exports, "colorToArray", { enumerable: true, get: function () { return colorConversion_1.colorToArray; } });
Object.defineProperty(exports, "arrayToColor", { enumerable: true, get: function () { return colorConversion_1.arrayToColor; } });
Object.defineProperty(exports, "colorToGray", { enumerable: true, get: function () { return colorConversion_1.colorToGray; } });
Object.defineProperty(exports, "grayToColor", { enumerable: true, get: function () { return colorConversion_1.grayToColor; } });
Object.defineProperty(exports, "colorToHex", { enumerable: true, get: function () { return colorConversion_1.colorToHex; } });
Object.defineProperty(exports, "hexToColor", { enumerable: true, get: function () { return colorConversion_1.hexToColor; } });
Object.defineProperty(exports, "colorToChromaColor", { enumerable: true, get: function () { return colorConversion_1.colorToChromaColor; } });
Object.defineProperty(exports, "nameToColor", { enumerable: true, get: function () { return colorConversion_1.nameToColor; } });
var helper_1 = require("./helper");
Object.defineProperty(exports, "random", { enumerable: true, get: function () { return helper_1.random; } });
Object.defineProperty(exports, "randomInt", { enumerable: true, get: function () { return helper_1.randomInt; } });
Object.defineProperty(exports, "clamp", { enumerable: true, get: function () { return helper_1.clamp; } });
Object.defineProperty(exports, "cloneDeep", { enumerable: true, get: function () { return helper_1.cloneDeep; } });
var degree_1 = require("./degree");
Object.defineProperty(exports, "rad2deg", { enumerable: true, get: function () { return degree_1.rad2deg; } });
Object.defineProperty(exports, "deg2rad", { enumerable: true, get: function () { return degree_1.deg2rad; } });
//# sourceMappingURL=index.js.map